config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :rooms do
    resources :viewings
    resources :bookings
  end

  resources :rmcats
  resources :extras
  resources :extracats
  resources :enquiries
  resources :additions

  root :to => redirect('/pages/home')
  get 'pages/home'
  get 'pages/contactus' => 'enquiries#new'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meadow View | Weddings</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="main-div">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <!-- if there is a user signed in -->
        <% if user_signed_in? %>
            <!-- if user is admin display navigation bar with all privilidges -->
            <% if not current_user.customer? %>
                <% if not current_user.admin? %>
                    <ul>
                      <li><a class="navbar-brand" href="/pages/home">Home</a></li>
                      <li>
                        <a class="navbar-brand" href="/rooms">Rooms</a>
                        <ul>
                          <li><a class="navbar-brand" href="/rooms">View Rooms</a></li>
                        </ul>
                      </li>
                      <li>
                        <a class="navbar-brand" href="/rmcats">Room Types</a>
                        <ul>
                          <li><a class="navbar-brand" href="/rmcats">View Room Types</a></li>
                          <li><a class="navbar-brand" href="/rmcats/new">New Room Type</a></li>
                        </ul>
                      </li>
                      <ul>
                        <li><a class="navbar-brand" href="/extras">Extras</a></li>
                        <li>
                          Account
                          <ul>
                            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-brand' %></li>
                            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-brand' %></li>
                          </ul>
                        </li>
                      </ul>
                <% end %>
            <% end %>
            <!-- if user is admin display navigation bar with all privilidges -->
            <% if current_user.admin? %>
                <ul>
                  <li><a class="navbar-brand" href="/pages/home">Home</a></li>
                  <li>
                    <a class="navbar-brand" href="/rooms">Rooms</a>
                    <ul>
                      <li><a class="navbar-brand" href="/rooms">View Rooms</a></li>
                      <li><a class="navbar-brand" href="/rooms/new">New Room</a></li>
                    </ul>
                  </li>
                  <li>
                    <a class="navbar-brand" href="/rmcats">Room Types</a>
                    <ul>
                      <li><a class="navbar-brand" href="/rmcats">View Room Types</a></li>
                      <li><a class="navbar-brand" href="/rmcats/new">New Room Type</a></li>
                    </ul>
                  </li>
                  <li><a class="navbar-brand" href="/pages/contactus">Contact us</a></li>
                  <ul>
                    <li><a class="navbar-brand" href="/extras">Extras</a></li>
                    <li>
                      <a class="navbar-brand" href="/extracats">Extra Types</a>
                      <ul>
                        <li><a class="navbar-brand" href="/extracats">View Extra Types</a></li>
                        <li><a class="navbar-brand" href="/extracats/new">New Extra Type</a></li>
                      </ul>
                    <li>
                      Account
                      <ul>
                        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-brand' %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-brand' %></li>
                      </ul>
                    </li>
                  </ul>
            <% end %>

            <!-- if a customer is signed in display navbar with sufficient privilidges -->
            <% if current_user.customer? %>
                <ul>
                  <li><a class="navbar-brand" href="/pages/home">Home</a></li>
                  <li><a class="navbar-brand" href="/extras">Extras</a></li>
                  <li>
                    <a class="navbar-brand" href="/rooms">Rooms</a>
                  </li>
                  <li><a class="navbar-brand" href="/pages/contactus">Contact us</a></li>
                  <li>
                    Account
                    <ul>
                      <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-brand' %></li>
                      <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-brand' %></li>
                    </ul>
                  </li>
                </ul>
            <% end %>
            <!-- else if not logged in -->
        <% else %>
            <ul>
              <li><a class="navbar-brand" href="/pages/home">Home</a></li>
              <li>
                <a class="navbar-brand" href="/rooms">Rooms</a>
              </li>
              <li><a class="navbar-brand" href="/pages/contactus">Contact us</a></li>
              <li><a class="navbar-brand" href="/extras">Extras</a></li>
              <li>
                Account
                <ul>
                  <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-brand' %></li>
                  <li><%= link_to "Login", new_user_session_path, :class => 'navbar-brand' %></li>
                </ul>
              </li>
            </ul>
        <% end %>
        <div class="login">
          <% if user_signed_in? %>
              Logged in as <%= current_user.customer_name %>.
              <% if current_user.admin? %>
                  Signed in as Admin.
              <% end %>
              <!-- <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-brand' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-brand' %> -->
          <% else %>
              <!-- <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-brand' %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-brand' %> -->
          <% end %>
        </div>
      </div>
    </div>
  </nav>
  <div class="title">
    <%= image_tag("logo.gif") %>
  </div>
  <div class="notice-alert">
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </div>
  <%= yield %>
</div>
</body>
</html>

app/views/pages/contactus.html.erb
<body>
<div class="contact-details">
  <h1>Contact Us</h1>

  <p>
    <br>
    If you have any queries, or are interested in any of our rooms, please get in touch with us on
    <strong> <a href="tel:011655554321">0116 555 54321</a> </strong>
    <br><br>
    We can also be contacted by email at <strong>
    <address><a href="mailto:enquiries@meadowview.co.uk">enquiries@meadowview.co.uk</a></address>
  </strong>
    <br><br>
    If you have an account you can make an enquiry using our form system, if not sign up or send us an email:
    <br><br>
    <% if not user_signed_in? %>
        <%= link_to "Sign up", new_user_registration_path %>
    <% end %>
    <% if current_user %>
        <%= render 'enquiries/form', enquiry: @enquiry %>
    <% end %>

    <% if current_user && current_user.admin? %>
        <%= link_to 'Show all enquiries', enquiries_path %>
    <% end %>
  </p>
</div>
</body>
<!--
might look at refactoring eventually.
Since it is a user that is signed in,
you could have a User has-many :enquiries and an Enquiry belongs_to a user.
This is where accepts_nested_attributes comes into play,
then you are using resourced routes, nested forms, etc
-->

app/views/pages/home.html.erb
<body>
<div class="landing-image">
  <div id="carousel" class="owl-carousel">
    <div> <%= image_tag("home_landing.jpg") %> </div>
    <div> <%= image_tag("lake_landing.jpg") %> </div>
    <div> <%= image_tag("bw_landing.jpg") %> </div>
    <div> <%= image_tag("cake_landing.jpg") %> </div>
    <div> <%= image_tag("ring_landing.jpg") %> </div>
    <div> <%= image_tag("car_landing.jpg") %> </div>
    <div> <%= image_tag("flower_landing.jpg") %> </div>
  </div>
</div>
<br>

<div class="footer">
  <a class="a-link" href="/admin">Dashboard</a>
</div>
</body>
<script>
    $(document).ready(function () {
        $("#carousel").owlCarousel({
            items: 1, //1 items above 1000px browser width
            autoPlay: true
        });
    });
</script>